### ISSUE TITLE
Long array definition with empty spaces in values assignment breaks indentation 

### ISSUE THREAD

**Issue by arnisjuraga** [gerardroche/sublime-php-grammar#34] opened 2015-09-14 12:11 UTC
I have strange problem - with this kind of "long" array definition, 
~~~php
<?php
class Test {
public function testFunction($product_id, $exclude = '') {
if ($product_id) {
$result = array(
'product_id'       => $query->row['product_id'],
'name'            => $query->row['name'],
'subtitle'         => $query->row['subtitle'],
'description'      => $query->row['description'],
'meta_description' => $query->row['meta_description'],
'meta_keyword'     => $query->row['meta_keyword'],
'tag'              => $query->row['tag'],
'model'            => $query->row['model'],
'sku'             => $query->row['sku'],
'upc'                => $query->row['upc'],
'ean'              => $query->row['ean'],
'jan'        => $query->row['jan'],
'a' => $query->row['a'],
'b' => $query->row['b'],
'c' => $query->row['c'],
'd' => $query->row['d'],
'f' => $query->row['f'],
'image'            => $query->row['image']);
echo "test";
}
}
}
~~~

Indentation works only till array definition closure.

Untill you delete "at least one" empty space character in any array element assigmen

~~~php
'product_id'---delete-one-space-here-e.g.-=> $query->row['product_id'],
~~~

Then, indentation works!!!  This is slosest I've got with debug.

**Comment by gerardroche** [comment] 2015-09-15 01:26
I'm sorry I don't understand what the issue is. 

When I take the code you provide, paste it into ST, select it all, and reindent it (`Edit > Line > Reindent`), it indents as expected.

When I delete any spaces it also doesn't change the indentation.

**Comment by arnisjuraga** [comment] 2015-09-16 08:24
I have tried again on fresh Sublime 3 installation, and youe are right - with my example it indents correctly. But - try to add even more assignment lines:
~~~
'x' => 'value',
~~~

At one point, it still breaks after last array closing bracket. Look at ```echo "test";``` line and brackets after that:

My result with even bigger array example:

~~~php
<?php
class Test {
	public function testFunction($product_id, $exclude = '') {
		if ($product_id) {
			$result = array(
				'product_id'       => $query->row['product_id'],
				'name'            => $query->row['name'],
				'subtitle'         => $query->row['subtitle'],
				'description'      => $query->row['description'],
				'meta_description' => $query->row['meta_description'],
				'meta_keyword'     => $query->row['meta_keyword'],
				'tag'              => $query->row['tag'],
				'model'            => $query->row['model'],
				'sku'             => $query->row['sku'],
				'upc'                => $query->row['upc'],
				'ean'              => $query->row['ean'],
				'jan'        => $query->row['jan'],
				'a' => $query->row['a'],
				'b' => $query->row['b'],
				'c' => $query->row['c'],
				'd' => $query->row['d'],
				'f' => $query->row['f'],
				'f' => $query->row['f'],
				'f' => $query->row['f'],
				'f' => $query->row['f'],
				'f' => $query->row['f'],
				'f' => $query->row['f'],
				'f' => $query->row['f'],
				'f' => $query->row['f'],
				'f' => $query->row['f'],
				'f' => $query->row['f'],
				'f' => $query->row['f'],
				'f' => $query->row['f'],
				'f' => $query->row['f'],
				'f' => $query->row['f'],
				'f' => $query->row['f'],
				'f' => $query->row['f'],
				'f' => $query->row['f'],
				'f' => $query->row['f'],
				'f' => $query->row['f'],
				'f' => $query->row['f'],
				'f' => $query->row['f'],
				'f' => $query->row['f'],
				'f' => $query->row['f'],
				'f' => $query->row['f'],
				'f' => $query->row['f'],
				'f' => $query->row['f'],
				'image'            => $query->row['image']);
echo "test";
}
}
}
~~~

**Comment by gerardroche** [comment] 2015-09-16 23:56
I can't reproduce it. I don't understand how the indentation ends up like that. You'll need to explain the steps to reproduce it. What do you mean by adding even more assignment lines? What content should I start with, where should place the cursor, what should I type, what are is the actual result and what is the expected result?

**Comment by arnisjuraga** [comment] 2015-09-17 09:25
I can reproduce it easily. Let's see:
Windows 7 32-bit, Virtualbox image. Fresh Windows 7 with updates.
1) Start Windows 7 
2) Install Sublime 3 latest (Build 3083)
3) Install Package Manager (will require restart of Sublime, because of "1 dependency installed")
4) Install "php-grammer" package
5) restart Sublime
6) Copy and Paste very long array definition code (from my second example)
7) Select all text, choose Edit > Line > Reindent.

Results will be as I have been posting before - problem with this line:

result:
~~~php
				'f' => $query->row['f'],
				'f' => $query->row['f'],
				'image'            => $query->row['image']);
echo "test";
}
}
}
~~~

expected result:
~~~php
				'f' => $query->row['f'],
				'f' => $query->row['f'],
				'image'            => $query->row['image']);
			echo "test";
		}
	}
}
~~~

**May be this is problem with Sublime?**
Because - it does not matter, either php-grammar is Enabled or Disabled, I have one more problem with such an array definition:

**This behavior is only with that long array definition**

~~~php
				'image'            => $query->row['image']);<-------------put cursor here
~~~

end press enter. Expected result: cursor must got to next line indented.

~~~php
				'f' => $query->row['f'],
				'f' => $query->row['f'],
				'image'            => $query->row['image']);
			<-------------------------- cursor must go to this position!
~~~

result:

~~~php
				'f' => $query->row['f'],
				'f' => $query->row['f'],
				'image'            => $query->row['image']);
<-------------------------- instead, cursor goes to the beginning of line!
~~~

Please, contact me PM, if You still cannot reproduce.

**Comment by arnisjuraga** [comment] 2015-09-17 10:02
Have posted issue to SublimeText, as this happens the same with Sublime PHP package and without php-grammar also! 
https://github.com/SublimeTextIssues/Core/issues/992

**Comment by gerardroche** [comment] 2015-09-17 10:12
Thanks. Sorry, I should have thought to ask what version of ST you were using. I can indeed reproduce it in Build 3083. It's fixed in Build 3095. 

ST uses a new syntax definition file format since 3083. php-grammar no longer supports the old syntax. php-grammar will continue to work with older versions of ST but new fixes and improvements will be not be backported to the old syntax.

**Comment by gerardroche** [comment] 2015-09-24 03:57
Closing this as it is fixed in the latest build, 3095.

**Closed by gerardroche** 2015-09-24 03:57 UTC
