### ISSUE TITLE
Arrays using square brackets does not indent

### ISSUE THREAD

**Issue by ssang** [gerardroche/sublime-php-grammar#86] opened 2016-02-25 18:46 UTC
Currently when I press enter inside square brackets, it does not indent on the next line.

````php
$foo = [
|
]
````

Expected:

````php
$foo = [
    |
]
````

**Comment by gerardroche** [comment] 2016-05-11 11:31
Duplicate of https://github.com/gerardroche/sublime-php-grammar/issues/7

**Closed by gerardroche** 2016-05-11 11:31 UTC
